/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jshc_waveprogressbar_utils_JNIUtil */

#ifndef _Included_com_jshc_waveprogressbar_utils_JNIUtil
#define _Included_com_jshc_waveprogressbar_utils_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jshc_waveprogressbar_utils_JNIUtil
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jshc_waveprogressbar_utils_JNIUtil_getMessage(JNIEnv *env, jobject)
{
    return env -> NewStringUTF("我的第一个JNI程序!");
};

#ifdef __cplusplus
}
#endif
#endif
